use_frameworks!

platform :ios, '9.0'

target 'ZHCodable_Example' do
  pod 'ZHCodable', :path => '../'

  target 'ZHCodable_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
